
package webservice;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MesEsbServiceImplService", targetNamespace = "http://impl.webservice.mesesb.saicmotor.com/", wsdlLocation = "http://10.68.13.64:8080/MES-ESB/ws/mesEsbWebService?wsdl")
public class MesEsbServiceImplService
    extends Service
{

    private final static URL MESESBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MESESBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName MESESBSERVICEIMPLSERVICE_QNAME = new QName("http://impl.webservice.mesesb.saicmotor.com/", "MesEsbServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.68.13.64:8080/MES-ESB/ws/mesEsbWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MESESBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        MESESBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public MesEsbServiceImplService() {
        super(__getWsdlLocation(), MESESBSERVICEIMPLSERVICE_QNAME);
    }

    public MesEsbServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MESESBSERVICEIMPLSERVICE_QNAME, features);
    }

    public MesEsbServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, MESESBSERVICEIMPLSERVICE_QNAME);
    }

    public MesEsbServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MESESBSERVICEIMPLSERVICE_QNAME, features);
    }

    public MesEsbServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MesEsbServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MesEsbService
     */
    @WebEndpoint(name = "MesEsbServiceImplPort")
    public MesEsbService getMesEsbServiceImplPort() {
        return super.getPort(new QName("http://impl.webservice.mesesb.saicmotor.com/", "MesEsbServiceImplPort"), MesEsbService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MesEsbService
     */
    @WebEndpoint(name = "MesEsbServiceImplPort")
    public MesEsbService getMesEsbServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.mesesb.saicmotor.com/", "MesEsbServiceImplPort"), MesEsbService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MESESBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw MESESBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return MESESBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
