
package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MesEsbService", targetNamespace = "http://webservice.mesesb.saicmotor.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MesEsbService {


    /**
     * 
     * @param arg0
     * @return
     *     returns webservice.MesEsbResponse
     */
    @WebMethod(action = "urn:DataSwitching")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dataSwitching", targetNamespace = "http://webservice.mesesb.saicmotor.com/", className = "webservice.DataSwitching")
    @ResponseWrapper(localName = "dataSwitchingResponse", targetNamespace = "http://webservice.mesesb.saicmotor.com/", className = "webservice.DataSwitchingResponse")
    public MesEsbResponse dataSwitching(
        @WebParam(name = "arg0", targetNamespace = "")
        MesEsbRequest arg0);

}
